### PR TITLE
WIP: ETHPrize responsive website

### LINKED ISSUE #3: Build Website
Use the template designed by Fedor in #1 and build it.

It is a simple one page website and we need it built by the 10th of March, so there is some time pressure on this bounty. 

The site needs to be mobile responsive and further context and copy will be provided to the person/people who agree to take this on.

## Links
1. [Figma](https://www.figma.com/file/FCakALK84WSxZB5QhvaV213e/ETHPrize?node-id=1%3A2) - The latest design version of the website. If you switch to "Code" view on the upper right corner, you can see the some of the specs. "Learn more" on the first screen is an anchor link to the About section. Links at the very bottom: Fedor Shkliarau (http://fedor.design/), Scott Webb (https://unsplash.com/@scottwebb)

2. [Readymag](https://readymag.com/shkliarau/995140/) - Prototype with animation how the effect of the effect from Tympanus and overall behavior.

3. [Tympanus](https://tympanus.net/Tutorials/CSSMaskTransition/index2.html) - effect for the hero image and second image in About section.

### PR DESCRIPTION
**Pull request by CS76**
Fixes #3 

This is a work in progress placeholder for the ETHPrize website based on the following resources

Figma - The latest design version of the website. If you switch to "Code" view on the upper right corner, you can see the some of the specs. "Learn more" on the first screen is an anchor link to the About section. Links at the very bottom: Fedor Shkliarau (http://fedor.design/), Scott Webb (https://unsplash.com/@scottwebb)

Readymag - Prototype with animation how the effect of the effect from Tympanus and overall behavior.

Tympanus - effect for the hero image and second image in About section.

### CODE REVIEW

**Comment by CS76** [comment]
Fix #3 

The code needs to be optimized and testing but its a good starting point for us. 
Let me know your thoughts.

**Comment by andytudhope** [comment]
@CS76 this is beginning to look really good. My biggest issue is that, as you scroll, there is still a weird border on the top, right, and bottom from the hero image that needs to be removed as it does not reflect the design accurately.:

screen shot 2018-03-10 at 12 39 27

We also need to put links into each of the `Partners` blocks and the `Contact` blocks:
https://status.im
https://truebit.io/
https://l4.ventures/

Will folow u with contact details shortly.

Next, there is some new copy we need to add/change, all captured here: https://docs.google.com/document/d/1qL26G8eeHd757OeIEczVwN9UHxLCpnHHgDxI5PnxOgc/edit

And, finally, I am going to be deploying this site via GitHub pages hopefully in the next few hours if you can manage these changes by then, so please go ahead and include the `gh-pages` package and the very, very simple `npm run deploy` script? If you don't know how to do this, don't stress, I can merge what you have here and set that part up myself.

**Comment by andytudhope** [comment]
Please also move all the icons into an `icons` folder if possible so that we have a cleaner directory structure? Will try to get through what I need to an at least push the copy changes to your branch.

**Comment by andytudhope** [comment]
Also, @CS76 - the alignment in the `About` section is very different from the design, and needs to be fixed too. I will add the correct copy - could you fix the alignment?

screen shot 2018-03-10 at 13 26 10

**Pull request merged**
